# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QiniuLogs < Formula
  desc "七牛云日志文件下载工具 - 基于用户ID搜索和下载日志文件"
  homepage "https://github.com/Nevermore130/rela-qiniu-logs"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.2/rela-qiniu-logs_0.2.2_darwin_amd64.tar.gz"
      sha256 "df7454afc69e0d9ea6446424630657d12a9fbef5b2d86764b19e22a1afb0beea"

      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.2/rela-qiniu-logs_0.2.2_darwin_arm64.tar.gz"
      sha256 "efe3ca692bd00579743987b9217a76b3465fef7afa4a69ab0f47adc21f9bc485"

      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.2/rela-qiniu-logs_0.2.2_linux_amd64.tar.gz"
      sha256 "fc4a890af80992e996776d7ff800a7c833c3180baf6bee26c31639dccde2dfae"
      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.2/rela-qiniu-logs_0.2.2_linux_arm64.tar.gz"
      sha256 "d20413bbbbddd2a36f988a3babd7d98be86039fcdf068f8600d9f13152b97d7a"
      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用前，请运行初始化配置:
        qiniu-logs init

      配置文件位置: ~/.qiniu-logs/config.yaml
    EOS
  end

  test do
    system "#{bin}/qiniu-logs", "--version"
  end
end
