# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QiniuLogs < Formula
  desc "七牛云日志文件下载工具 - 基于用户ID搜索和下载日志文件"
  homepage "https://github.com/Nevermore130/rela-qiniu-logs"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.1/rela-qiniu-logs_0.2.1_darwin_amd64.tar.gz"
      sha256 "46593fc5be84847c0cafff77154bb2b85eadd72126c7c33381c06eef5e19767d"

      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.1/rela-qiniu-logs_0.2.1_darwin_arm64.tar.gz"
      sha256 "4fa76f3d0123e9dc806fa5063112abe62ee7f94b31e322f580bb1b61007e9469"

      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.1/rela-qiniu-logs_0.2.1_linux_amd64.tar.gz"
      sha256 "ddca62f4202cc8e461dbe8dad408371de9259a313fdc66b892ad8ea80092da23"
      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.2.1/rela-qiniu-logs_0.2.1_linux_arm64.tar.gz"
      sha256 "21ef087022bcb0f81476a59e43f1d1dba600139d6abafbdb7d27cbf236b1c384"
      define_method(:install) do
        bin.install "qiniu-logs"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用前，请运行初始化配置:
        qiniu-logs init

      配置文件位置: ~/.qiniu-logs/config.yaml
    EOS
  end

  test do
    system "#{bin}/qiniu-logs", "--version"
  end
end
