# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QiniuLogs < Formula
  desc "七牛云日志文件下载工具 - 基于用户ID搜索和下载日志文件"
  homepage "https://github.com/Nevermore130/rela-qiniu-logs"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.1.5/rela-qiniu-logs_0.1.5_darwin_amd64.tar.gz"
      sha256 "5af23eeff0bff84fad912d288ec51e0ffd7db94729f4cb45e3fbf0606a398b6c"

      def install
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.1.5/rela-qiniu-logs_0.1.5_darwin_arm64.tar.gz"
      sha256 "157a6abca600b42a96ef9ca0a22409a804493f69260188a41e4aebe3ee3c3554"

      def install
        bin.install "qiniu-logs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.1.5/rela-qiniu-logs_0.1.5_linux_amd64.tar.gz"
      sha256 "ec555ff21797a11e43f304e0b8de91561bedbdaeae95f3a8e19a7adfe94690cf"
      def install
        bin.install "qiniu-logs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nevermore130/rela-qiniu-logs/releases/download/v0.1.5/rela-qiniu-logs_0.1.5_linux_arm64.tar.gz"
      sha256 "3820375ab2b688db9e051a6793712ccedecaef19ec6d29b723a8582ca316549f"
      def install
        bin.install "qiniu-logs"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用前，请运行初始化配置:
        qiniu-logs init

      配置文件位置: ~/.qiniu-logs/config.yaml
    EOS
  end

  test do
    system "#{bin}/qiniu-logs", "--version"
  end
end
